flutter_application_path = '../my_flutter'
load File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')

target 'TodaysApp' do
    install_all_flutter_pods(flutter_application_path)
  end